#!/bin/bash

yay -S visual-studio-code-bin --noconfirm

code --install-extension aaron-bond.better-comments
code --install-extension antfu.icons-carbon
code --install-extension attilabuti.vscode-mjml
code --install-extension austenc.tailwind-docs
code --install-extension bradlc.vscode-tailwindcss
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension ChakrounAnas.turbo-console-log
code --install-extension christian-kohler.path-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension coolbear.systemd-unit-file
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension doublefint.pgsql
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension emilast.LogFileHighlighter
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixfbecker.php-pack
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-complete-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension ghmcadams.lintlens
code --install-extension GrapeCity.gc-excelviewer
code --install-extension gurayyarar.expressjs-4-snippets
code --install-extension hollowtree.vue-snippets
code --install-extension HookyQR.beautify
code --install-extension isudox.vscode-jetbrains-keybindings
code --install-extension JakeWilson.vscode-cdnjs
code --install-extension jock.svg
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension jundat95.react-native-snippet
code --install-extension k--kato.intellij-idea-keybindings
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension kyleengler.docthis-shockoe
code --install-extension leizongmin.node-module-intellisense
code --install-extension luwenjiechn.nunjucks-vscode-snippets
code --install-extension marlongerson.jetbrains-icons
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension mrorz.language-gettext
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension naumovs.color-highlight
code --install-extension navin-moorthy.vscode-css-snippets
code --install-extension octref.vetur
code --install-extension pflannery.vscode-versionlens
code --install-extension rickrich.bootsnip
code --install-extension ritwickdey.LiveServer
code --install-extension rocketseat.rocketseatreactnative
code --install-extension ronnidc.nunjucks
code --install-extension sdras.vue-vscode-snippets
code --install-extension tariky.easy-snippet-maker
code --install-extension thekalinga.bootstrap4-vscode
code --install-extension tomoki1207.pdf
code --install-extension tomphilbin.gruvbox-themes
code --install-extension vincaslt.highlight-matching-tag
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.change-case
code --install-extension xabikos.JavaScriptSnippets

